[Title]
Text=List of skins

[Description]
Text=Customize what skins to be loaded when IdleStyle activates.

[Subtitle]
Meter=String
X=r
Y=(#sec.P#)R
Text=How can I add skins to the list?
FontSize=(15*#Sec.S#)
MeterStyle=Sec.String:S

[Description2]
Meter=String
Text=1. Click on the green pen icon and open a skin from the Rainmeter Skins folder. The file extension must be .ini.#CRLF#2. Activate the skin you selected and move it to the position you would like it to be#CRLF#3. Deactivate it and it will show up when you go Idle!
X=r
Y=(#sec.P#)R
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S

[Description3]
Meter=String
Text=Any skin hooked to IdleStyle will not be available for widget use. To revert this, remove the skin from the list, activate it and set it's position to normal from the Rainmeter manage panel.
X=r
Y=(#sec.P#)R
FontSize=(12*#Sec.S#)
MeterStyle=Sec.String:S