[Variables]
@includegVar2=#SKINSPATH##JaxCore\@Resources\gVars\Weather.inc
@includegVar3=#SKINSPATH##JaxCore\@Resources\gVars\WeatherAPIKey.inc
BackgroundColor=50,50,50
BackgroundOpacity=50
Color1=255,0,0
Blur=Acrylic
WeatherLocation=Hong Kong
WeatherUnits=Metric
Language=en

24HTime=1
DetailsFlip=0

IconStyle=Color

Scale=1.00
; A size multiplier for the skin. Please stick to increments of 0.25, so "1.25", "1.5", "1.75" etc.
Alignment=Center
; The alignment of the skin inside of the skin area.
; Valid values are "Left", "Center" and "Right".
; ================================================
DateSize=14
; The size of the date text in pixels.
CurrentTemperatureSize=144
; The size of the current temperature text in pixels.
CurrentPhraseSize=16
; The size of the current phrase text in pixels.
NarrativeSize=12
; The size of the narrative text in pixels.
DetailsIconSize=18
; The size of the details icons in pixels.
DetailsSize=14
; The size of the details text in pixels.
DailyWeekdaySize=12
; The size of the weekday text of the forecast in pixels.
DailyIconSize=36
; The size of the icons of the forecast in pixels.
DailyTemperatureSize=10

SkinWidth=320
; The width of the (draggable) skin area in pixels.
